//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace ClothRenting2.Admin
{
    public partial class AdminDashboard
    {

        /// <summary>
        /// lblUsers control
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUsers;

        /// <summary>
        /// lblProducts control
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblProducts;

        /// <summary>
        /// lblOrders control
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOrders;

        /// <summary>
        /// lblRevenue control
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblRevenue;

    }
}