//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace ClothRenting2.Admin
{
    public partial class ManageOrders
    {
        /// <summary>
        /// gvOrders control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvOrders;

        protected global::System.Web.UI.WebControls.Label lblTotal;
    }
}