//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace ClothRenting2.Admin
{
    public partial class ManageProducts
    {
        protected global::System.Web.UI.WebControls.HiddenField hfProductID;

        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;

        protected global::System.Web.UI.WebControls.TextBox txtProductName;

        protected global::System.Web.UI.WebControls.TextBox txtDescription;

        protected global::System.Web.UI.WebControls.TextBox txtPrice;

        protected global::System.Web.UI.WebControls.FileUpload fuImage;

        protected global::System.Web.UI.WebControls.Button btnSave;

        protected global::System.Web.UI.WebControls.GridView gvProducts;
    }
}