//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace ClothRenting2.Admin
{
    public partial class ViewFeedback
    {
        /// <summary>
        /// gvFeedback control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvFeedback;
    }
}