//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace ClothRenting2
{
    public partial class Categories
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Repeater rptCategories;
    }
}