//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace ClothRenting2
{
    public partial class ContactUs
    {
        protected global::System.Web.UI.WebControls.Label lblMsg;

        protected global::System.Web.UI.WebControls.TextBox txtName;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        protected global::System.Web.UI.WebControls.TextBox txtMessage;

        protected global::System.Web.UI.WebControls.Button btnSend;
    }
}